// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyD23fxrL7bzNz2vDrKTIkHnTC_d2AsNos4',
    appId: '1:921765226482:web:9a9da225e7047e21dd6d6b',
    messagingSenderId: '921765226482',
    projectId: 'phone-auth-82e5d',
    authDomain: 'phone-auth-82e5d.firebaseapp.com',
    storageBucket: 'phone-auth-82e5d.appspot.com',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyCCDJK2pltCzZuPOw5Uq5unqA7Kg3tTVrA',
    appId: '1:921765226482:android:2cabc3e5f535e82bdd6d6b',
    messagingSenderId: '921765226482',
    projectId: 'phone-auth-82e5d',
    storageBucket: 'phone-auth-82e5d.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyA7wm9JXuV9X4vR4d62kZo4FCkAFq8Jesc',
    appId: '1:921765226482:ios:54b6b56b16e4c04add6d6b',
    messagingSenderId: '921765226482',
    projectId: 'phone-auth-82e5d',
    storageBucket: 'phone-auth-82e5d.appspot.com',
    iosBundleId: 'com.example.mobileLogin',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyA7wm9JXuV9X4vR4d62kZo4FCkAFq8Jesc',
    appId: '1:921765226482:ios:183c0940e324fd7bdd6d6b',
    messagingSenderId: '921765226482',
    projectId: 'phone-auth-82e5d',
    storageBucket: 'phone-auth-82e5d.appspot.com',
    iosBundleId: 'com.example.mobileLogin.RunnerTests',
  );
}
